name: poc_sql_database
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Framework para gerência de estado
  get: ^4.6.5

  #Libs dos bancos de dados
  floor: ^1.4.1
  drift: ^2.7.0

  #Libs auxiliares
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  #Libs de UI
  flutter_svg: ^2.0.2
  syncfusion_flutter_charts: ^21.1.39
  syncfusion_flutter_core: ^21.1.39
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #Geradores de código
  floor_generator: ^1.4.1
  drift_dev: ^2.7.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: asap
      fonts:
        - asset: assets/font/asap.ttf
        - asset: assets/font/asap_bold.ttf
          weight: 700

